

#define GETTING_STARTED_BG_COLOR [UIColor colorWithRed:0.0463483f green:0.377801f blue:0.610586f alpha:1.0f]

#define GETTING_STARTED_MOCK_PAGE_ALPHA_BACKGROUND 0.15f
#define GETTING_STARTED_MOCK_PAGE_ALPHA_LINES 0.5f
#define GETTING_STARTED_MOCK_PAGE_ALPHA_LOGO 0.5f
#define GETTING_STARTED_MOCK_PAGE_LINE_WIDTH 3.0f

#define GETTING_STARTED_MOCK_BAD_PHOTO_ALPHA_FRONT 0.05f
#define GETTING_STARTED_MOCK_BAD_PHOTO_ALPHA_BACK 0.15f

#define GETTING_STARTED_HEADING_FONT_SIZE ((UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) ? 17.0f : 15.0f)
#define GETTING_STARTED_SUB_HEADING_FONT_SIZE ((UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) ? 15.0f : 13.0f)

#define GETTING_STARTED_LABEL_LINE_SPACING 2.8f
