

#define GETTING_STARTED_IS_IPAD (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)

#define GETTING_STARTED_BG_COLOR [UIColor colorWithRed:0.0463483f green:0.377801f blue:0.610586f alpha:1.0f]

#define GETTING_STARTED_MOCK_PAGE_ALPHA_BACKGROUND 0.15f
#define GETTING_STARTED_MOCK_PAGE_ALPHA_LINES 0.5f
#define GETTING_STARTED_MOCK_PAGE_ALPHA_LOGO 0.5f
#define GETTING_STARTED_MOCK_PAGE_LINE_WIDTH 3.0f

#define GETTING_STARTED_MOCK_BAD_PHOTO_ALPHA_FRONT 0.05f
#define GETTING_STARTED_MOCK_BAD_PHOTO_ALPHA_BACK 0.15f

#define GETTING_STARTED_HEADING_FONT_SIZE (GETTING_STARTED_IS_IPAD ? 26.0f : 15.0f)
#define GETTING_STARTED_SUB_HEADING_FONT_SIZE (GETTING_STARTED_IS_IPAD ? 22.0f : 13.0f)

#define GETTING_STARTED_LABEL_LINE_SPACING 2.8f

#define GETTING_STARTED_SPACE_BELOW_ANIMATION (GETTING_STARTED_IS_IPAD ? 60.0f : 40.0f)
#define GETTING_STARTED_SPACE_BELOW_HEADING (GETTING_STARTED_IS_IPAD ? 32.0f : 22.0f)

#define GETTING_STARTED_WHATISCOMMONS_MOCKPAGE_ANIMATION_DELAY 0.55f
#define GETTING_STARTED_WHATPHOTOS_MOCKBADPHOTO_ANIMATION_DELAY 0.0f
#define GETTING_STARTED_GOTIT_MOCKPAGE_ANIMATION_DELAY 0.10f
#define GETTING_STARTED_GOTIT_MOCKBADPHOTO_ANIMATION_DELAY 0.75f
#define GETTING_STARTED_GOTIT_YESBUTTONATTENTION_ANIMATION_DELAY 1.85f

#define GETTING_STARTED_WHATISCOMMONS_ANIMATION_SCALE (GETTING_STARTED_IS_IPAD ? 1.5f : 1.0f)
#define GETTING_STARTED_WHATPHOTOS_ANIMATION_SCALE (GETTING_STARTED_IS_IPAD ? 1.5f : 1.0f)
#define GETTING_STARTED_GOTIT_ANIMATIONS_SCALE (GETTING_STARTED_IS_IPAD ? 1.0f : 0.5f)

#define GETTING_STARTED_GOTIT_ANIMATIONS_SPACE_BETWEEN (GETTING_STARTED_IS_IPAD ? 16.0f : 8.0f)

#define GETTING_STARTED_VERTICAL_SPACE_BETWEEN_LABELS (GETTING_STARTED_IS_IPAD ? 0.05f : 0.06f)
#define GETTING_STARTED_VERTICAL_SPACE_BETWEEN_HALVES (GETTING_STARTED_IS_IPAD ? 0.07f : 0.08f)

#define GETTING_STARTED_LABEL_WIDTH_MULTIPLIER (GETTING_STARTED_IS_IPAD ? 1.3f : 0.75f)